### ISSUE TITLE
No split screen/screen rect support?

### ISSUE THREAD

**Issue by davidkroukamp** [alelievr/HDRP-UI-Camera-Stacking#14]
I am making a split screen game using cinemachine, and all seems well, except that the HDRP UI Camera doesnt seem to account for the camera that its rendering Screen rect (as this has been halfed for each of my 2 cameras).

I've looked at the code, I assume I need to change the internal texture size (as Im using the automatic option) to something other then camera.pixelWidth and camera.pixelHeight? or is there another way?

**Comment by alelievr** [comment]
Hello, I pushed a change to simplify the split-screen setup: https://github.com/alelievr/HDRP-UI-Camera-Stacking/tree/1.3.0
You can take a look at the SplitScreen scene if you want an example. Also don't forget to have matching camera rects between the UI camera and main camera otherwise you'll experience streching

**Comment by davidkroukamp** [comment]
Thanks alot, will definitely give a it go as the clipping of my HUD right now when I'm close to objects just won't cut it for a release! Appreciate the effort!
